# Generated by Django 4.2.5 on 2023-09-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologia',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
